# Generated by Django 4.1.7 on 2023-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=250, null=True)),
                ('operator_username', models.CharField(max_length=250, null=True)),
                ('operator_name', models.CharField(max_length=250, null=True)),
                ('student_prn_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=250, null=True)),
                ('pay_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[(' Cash', ' Cash'), (' Phone Pay', ' Phone Pay'), (' Google Pay', ' Google Pay'), (' Amazone Pay', ' Amazone Pay'), ('Other Online', 'Other Online')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount_word', models.CharField(max_length=250)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_remark', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DB_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2028-28', '2028-28')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='academic_session_institute',
            field=models.CharField(choices=[('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2028-28', '2028-28')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='academic_session_staff',
            field=models.CharField(choices=[('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2028-28', '2028-28')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='academic_session',
            field=models.CharField(blank=True, choices=[('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2028-28', '2028-28')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institute_name_staff',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institute_name_student',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_dist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_taluka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_collage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_collage_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_dist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_taluka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_village',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(choices=[('1st Standerd', '1st Standerd'), ('2nd Standerd', '2nd Standerd'), ('3rd Standerd', '3rd Standerd'), ('4th Standerd', '4th Standerd'), ('6th Standerd', '6th Standerd'), ('7th Standerd', '7th Standerd'), ('8th Standerd', '8th Standerd'), ('9th Standerd', '9th Standerd'), ('10th Standerd', '10th Standerd'), ('11th Standerd', '11th Standerd'), ('12th Standerd', '12th Standerd')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institute_profile',
            field=models.ImageField(blank=True, null=True, upload_to='institute_profile/'),
        ),
    ]
