# Generated by Django 4.1.7 on 2023-04-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0002_db_fees_db_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institute_owner',
        ),
    ]
