# Generated by Django 4.1.7 on 2023-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0005_db_fees_pay_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_fees',
            name='pay_remark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
