# Generated by Django 4.1.7 on 2023-04-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0006_alter_db_fees_pay_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_fees',
            old_name='pay_date',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='db_fees',
            old_name='pay_remark',
            new_name='received_remark',
        ),
    ]
