# Generated by Django 4.1.7 on 2023-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0008_rename_amount_db_fees_received_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fees',
        ),
        migrations.AddField(
            model_name='db_fees',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='db_fees',
            name='fees_remark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
