# Generated by Django 4.1.7 on 2023-04-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0009_remove_customuser_fees_db_fees_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_fees',
            old_name='fees',
            new_name='add_fees',
        ),
    ]
