# Generated by Django 4.1.7 on 2023-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0010_rename_fees_db_fees_add_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_fees',
            name='student_prn_no',
            field=models.IntegerField(null=True),
        ),
    ]
