# Generated by Django 4.1.7 on 2023-04-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0012_db_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_subjects',
            old_name='subject_class',
            new_name='class_name',
        ),
    ]
