# Generated by Django 4.1.7 on 2023-04-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0015_db_result_db_subjects_min_marks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_Subjects',
        ),
    ]
