# Generated by Django 4.1.7 on 2023-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0020_remove_db_result_passing_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Schedule_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('exam_title', models.CharField(max_length=100, null=True)),
                ('exam_start_date', models.DateField(null=True)),
                ('exam_end_date', models.DateField(null=True)),
            ],
        ),
    ]
