# Generated by Django 4.1.7 on 2023-04-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0023_rename_exam_name_db_result_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_prn_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
