# Generated by Django 4.1.7 on 2023-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0025_db_fees_academic_session_db_result_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_schedule_exam',
            name='academic_session',
            field=models.CharField(default='2022-23', max_length=100, null=True),
        ),
    ]
