# Generated by Django 4.1.7 on 2023-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0029_alter_customuser_academic_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='academic_session_institute',
        ),
        migrations.AddField(
            model_name='db_result',
            name='student_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
