# Generated by Django 4.1.7 on 2023-04-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0030_remove_customuser_academic_session_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_schedule_exam',
            name='academic_session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
