# Generated by Django 4.1.7 on 2023-04-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0033_remove_customuser_institute_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institute_name_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='institute_name_student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
    ]
