# Generated by Django 4.1.7 on 2023-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0036_customuser_institute_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=100, null=True)),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('student_prn_no', models.CharField(max_length=100, null=True)),
                ('attendance_date', models.CharField(max_length=100, null=True)),
                ('attendance_status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='db_fees',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Phone Pay', 'Phone Pay'), ('Google Pay', 'Google Pay'), ('Amazone Pay', 'Amazone Pay'), ('Other Online', 'Other Online')], max_length=50),
        ),
    ]
