# Generated by Django 4.1.7 on 2023-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0037_db_attendance_alter_db_fees_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_attendance',
            name='attendance_status',
            field=models.BooleanField(default=False),
        ),
    ]
