# Generated by Django 4.1.7 on 2023-04-17 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0038_alter_db_attendance_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_attendance',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='db_attendance',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='db_attendance',
            name='student_prn_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
