# Generated by Django 4.1.7 on 2023-04-17 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0039_remove_db_attendance_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_attendance',
            name='student_prn_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='student_prn_no'),
        ),
    ]
