# Generated by Django 4.1.7 on 2023-04-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0042_db_attendance_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_fees',
            name='date_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
