# Generated by Django 4.1.7 on 2023-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0043_db_fees_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_fees',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
