# Generated by Django 4.1.7 on 2023-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0046_db_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_attendance',
            name='attendance_status',
        ),
    ]
