# Generated by Django 4.1.7 on 2023-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0047_remove_db_attendance_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
