# Generated by Django 4.1.7 on 2023-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0049_db_web_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_web_notification',
            name='academic_session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
