# Generated by Django 4.1.7 on 2023-04-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0052_alter_db_web_notification_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_web_notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
