# Generated by Django 4.1.7 on 2023-04-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0054_alter_db_web_notification_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_web_notification',
            name='date_time',
        ),
    ]
