# Generated by Django 4.1.7 on 2023-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0055_remove_db_web_notification_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_web_notification',
            name='date_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
