# Generated by Django 4.1.7 on 2023-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0057_alter_db_web_notification_notification_valid_up_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_attendance',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_fees',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_result',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_schedule_exam',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_subjects',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_web_notification',
            name='institute_code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
