# Generated by Django 4.1.7 on 2023-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0058_customuser_institute_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_prn_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
