# Generated by Django 4.1.7 on 2023-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0060_alter_db_fees_student_prn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institute_is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
