# Generated by Django 4.1.7 on 2023-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0062_customuser_tour_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_institute_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
