# Generated by Django 4.1.7 on 2023-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0063_customuser_is_institute_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
