# Generated by Django 4.1.7 on 2023-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0064_alter_customuser_staff_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_fees',
            name='received_amount',
            field=models.IntegerField(null=True),
        ),
    ]
