# Generated by Django 4.1.7 on 2023-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0066_alter_db_fees_received_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_fees',
            name='amount_word',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
